sudo: required
services:
  - docker

before_install:
  - docker build -t tejasgowda27/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true tejasgowda27/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-447179161595"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    